# Generated by Django 5.1.7 on 2025-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('desc', models.TextField(blank=True, default='', null=True)),
                ('pic', models.ImageField(upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
